name: .Net Objects Publish and Deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    environment: production

    services:
      sql.server:
        image: mcr.microsoft.com/mssql/server:2019-latest
        env:
          SA_PASSWORD: UltranacoLabs.1
          ACCEPT_EULA: Y
        ports:
          - "1433:1433"

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.300
          
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build -c Release --no-restore
      - name: Test
        run: |
          dotnet test -c Release --no-build --verbosity normal
      - name: Pack
        run: |
          cd Ultranaco.Database.SQLServer
          dotnet pack -c Release
      - name: Publish Nuget to GitHub registry
        run: |
          cd Ultranaco.Database.SQLServer
          dotnet nuget push ./bin/Release/*.nupkg --source "https://api.nuget.org/v3/index.json" --api-key ${NUGET_TOKEN} --skip-duplicate --no-symbols
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
      - name: View Contents
        run: tree
